// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ConfirmationController from "./confirmation_controller"
application.register("confirmation", ConfirmationController)

import ToasterController from "./toaster_controller"
application.register("toaster", ToasterController)

import QuoteEditorController from "./quote_editor_controller"
application.register("quote-editor", QuoteEditorController)
